# Generated by Django 5.2 on 2025-04-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='freelancer_images/')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('work_experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='myapp.category')),
            ],
        ),
    ]
